name: CI/CD Pipeline
on:
  push:
    branches:
      - main
 
jobs:
  build-and-push:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag groupe2:${{ github.sha }}
 
      - name: Log in to Harbor Container Registry
        run: echo "B4teau123!" | docker login harbor.kakor.ovh -u ipi --password-stdin
 
      - name: Build and push Docker image
        run: |
          docker build -t harbor.kakor.ovh/ipi/groupe2:${{ github.sha }} .
          docker push harbor.kakor.ovh/ipi/groupe2:${{ github.sha }}

  scan:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy
 
      - name: Scan Docker image with Trivy
        run: trivy image harbor.kakor.ovh/ipi/groupe2:${{ github.sha }}
 
      - name: Continue on error (don't stop pipeline)
        if: failure()
        run: echo "Security scan failed, but continuing pipeline."

  deploy:
    runs-on: ubuntu-latest
    needs: scan
    steps:
      - name: Deploy on Openshift
        run: |
          oc login https://api.openshift.kakor.ovh:6443 --token=sha256~VSPHm-ydRnSXHoIf3hbFbiyOptjNd7KL1vN8tJYaTYE --insecure-skip-tls-verify
          oc apply -f kubernetes-manifest/deployment.yaml -n projet-gp-2
          oc apply -f kubernetes


